StreamMaxLength 2048M
MaxFileSize 2048M
MaxScanSize 2048M
MaxEmbeddedPE 2048M
PCREMaxFileSize 2048M
PidFile /run/lock/clamd.pid
LocalSocket /run/clamav/clamd.sock
TCPSocket 3310
#TCPAddr 0.0.0.0
User clamav
#Debug true
