version: "2.2"

services:
  clamav-server:
    image: clamav/clamav
    volumes:
      - ./clamd.conf:/etc/clamav/clamd.conf
  clamav:
    image: jreinartz/clamav-rest
    environment:
      HOST: clamav-server
      # example for setting the maximal upload size to about 80MB:
      MAX_STREAM_SIZE: 80100100
    ports:
      - 5000:80